### ISSUE TITLE
Failed to activate the busy-signal package

### ISSUE THREAD

**Issue by valkyriweb** [steelbrain/busy-signal#20]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [busy-signal](https://github.com/steelbrain/busy-signal) package 1.3.0

### Stack Trace

Failed to activate the busy-signal package

```
At ENOENT: no such file or directory, lstat '/Users/ilovebabu/Library/Caches/com.github.atom.ShipIt/update.pqeRtds'

Error: ENOENT: no such file or directory, lstat '/Users/ilovebabu/Library/Caches/com.github.atom.ShipIt/update.pqeRtds'
    at Error (native)
    at fs.lstatSync (fs.js:982:18)
    at Object.fs.lstatSync (ELECTRON_ASAR.js:239:16)
    at realpathSync (fs.js:1657:19)
    at Object.fs.realpathSync (ELECTRON_ASAR.js:326:24)
    at Function.Module._findPath (module.js:167:25)
    at Module._resolveFilename (module.js:453:25)
    at Module._resolveFilename (/Users/ilovebabu/Library/Caches/com.github.atom.ShipIt/update.pqeRtds/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Object.exports.getCachePath (/app.asar/src/babel.js:30:58)
    at Object.getCachePath (/app.asar/src/package-transpilation-registry.js:45:27)
    at compileFileAtPath (/app.asar/src/compile-cache.js:85:30)
    at /app.asar/src/compile-cache.js:215:18)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:207:16)
    at /app.asar/src/package.js:190:32
    at Package.module.exports.Package.measure (/app.asar/src/package.js:96:15)
    at /app.asar/src/package.js:183:26
    at Package.module.exports.Package.activate (/app.asar/src/package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/app.asar/src/package-manager.js:550:34)
    at /app.asar/src/package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (/app.asar/src/config.js:337:18)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.29.22 
atom-ternjs 0.18.2 
busy-signal 1.3.0 
emmet 2.4.3 
git-plus 7.4.0 
git-time-machine 1.5.9 
intentions 1.1.2 
linter 2.1.4 
linter-bootlint 1.0.4 
linter-csslint 1.3.4 
linter-eslint 8.1.6 
linter-htmlhint 1.3.3 
linter-jsonlint 1.3.0 
linter-php 1.3.2 
linter-pylint 2.0.1 
linter-rubocop 2.0.0 
linter-sass-lint 1.7.4 
linter-tidy 2.3.1 
linter-ui-default 1.2.3 
minimap 4.27.1 
pigments 0.39.1 
terminal-plus 0.14.5 
turbo-javascript 1.4.0 
wakatime 6.0.13 
```

**Comment by steelbrain** [comment]
Atom internal error, I don't even know what's crashing but a restart should fix it, if it doesn't uninstall and reinstall this package. Also make sure that a bug like this is open in Atom repo (if not, please open it) to make sure Atom folk know about this

**Comment by valkyriweb** [comment]
Ok I will do, sorry I am not sure why it is throwing this issue at me, it
seems to be working now.

I reinstalled atom and reinstalled the package.

Kind Regards,

Luke

**Comment by cruzlauroiii** [comment]
still an error: 
please reopen and fix.
compiled using "5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Atom/1.18.0-dev-1f3bb12a1 Chrome/56.0.2924.87 Electron/1.6.7 Safari/537.36"
